name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure Build Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --locked

      - name: Configure artifact
        id: configure
        shell: bash
        run: |
          suffix=${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          
          raw_file="fill-build-hasher-${{ runner.arch }}-${{ matrix.os }}${suffix}"
          file_lower=$(echo "$raw_file" | tr '[:upper:]' '[:lower:]')
          echo "file_name=${file_lower}" >> $GITHUB_ENV

          mv target/release/fill-build-hasher${suffix} target/release/${file_lower}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: target/release/${{ env.file_name }}
          archive: false
